// KoMES — 비급여(미용·다이어트) 시드 데이터
// 카테고리: 미용 / 다이어트 / 체형 / 피부 / 모발
// 단회·소규모 시술을 다룸 (패키지 관리와 구분)

const NC_CATEGORIES = [
  { key: "beauty",   label: "미용",     icon: "sparkles",    tone: "pink"   },
  { key: "diet",     label: "다이어트", icon: "scale",       tone: "pine"   },
  { key: "body",     label: "체형",     icon: "activity",    tone: "slate"  },
  { key: "skin",     label: "피부",     icon: "droplet",     tone: "bronze" },
  { key: "hair",     label: "모발",     icon: "scissors",    tone: "marine" },
];

const NC_TONES = {
  pine:   { bg: "var(--accent-pine-bg)",   border: "var(--accent-pine-border)",   fg: "var(--accent-pine)"   },
  slate:  { bg: "var(--accent-slate-bg)",  border: "var(--accent-slate-border)",  fg: "var(--accent-slate)"  },
  bronze: { bg: "var(--amber-500-bg)",     border: "var(--amber-500-border)",     fg: "var(--amber-700)"     },
  marine: { bg: "var(--accent-marine-bg)", border: "var(--accent-marine-border)", fg: "var(--accent-marine)" },
  pink:   { bg: "var(--pink-100)",         border: "var(--pink-200)",             fg: "var(--pink-700)"      },
};

// ── 시술 카탈로그 ────────────────────────────────────────────────
const NC_PROCEDURES = [
  // 미용 (Beauty)
  { id: "nc-1", code: "BT-FA-01", name: "안면 미용침", category: "beauty",
    tagline: "리프팅·잔주름·V라인 · 60분",
    duration: 60, price: 88000, memberPrice: 79200,
    room: "미용실 A", staff: "이지영 부원장",
    consult: false, recommend: 6,
    monthlySales: 142, monthlyRevenue: 12_496_000,
    badge: "BEST" },
  { id: "nc-2", code: "BT-TH-01", name: "매선 요법 (안면)", category: "beauty",
    tagline: "PDO 매선 · 안면 리프팅",
    duration: 45, price: 280000, memberPrice: 252000,
    room: "시술실 1", staff: "김민준 원장",
    consult: true, recommend: 4,
    monthlySales: 38, monthlyRevenue: 10_640_000 },
  { id: "nc-3", code: "BT-TH-02", name: "V라인 매선", category: "beauty",
    tagline: "턱선·심부 매선",
    duration: 50, price: 350000, memberPrice: 315000,
    room: "시술실 1", staff: "김민준 원장",
    consult: true, recommend: 4,
    monthlySales: 22, monthlyRevenue: 7_700_000 },
  { id: "nc-4", code: "BT-PC-01", name: "미백 약침", category: "beauty",
    tagline: "기미·잡티 케어 · 20분",
    duration: 20, price: 55000, memberPrice: 49500,
    room: "약침실", staff: "이지영 부원장",
    consult: false, recommend: 10,
    monthlySales: 86, monthlyRevenue: 4_730_000 },
  { id: "nc-5", code: "BT-PC-02", name: "다크서클 약침", category: "beauty",
    tagline: "눈가 혈류 개선 · 15분",
    duration: 15, price: 45000, memberPrice: 40500,
    room: "약침실", staff: "이지영 부원장",
    consult: false, recommend: 8,
    monthlySales: 54, monthlyRevenue: 2_430_000 },

  // 다이어트 (Diet)
  { id: "nc-6", code: "DT-HM-01", name: "비만 한약 (1개월)", category: "diet",
    tagline: "체질별 처방 · 30첩",
    duration: 30, price: 380000, memberPrice: 342000,
    room: "상담실 2", staff: "박서윤 원장",
    consult: true, recommend: 12,
    monthlySales: 78, monthlyRevenue: 29_640_000,
    badge: "BEST" },
  { id: "nc-7", code: "DT-AC-01", name: "다이어트 침", category: "diet",
    tagline: "복부·하체 침 자극 · 40분",
    duration: 40, price: 60000, memberPrice: 54000,
    room: "침실 B", staff: "이지영 부원장",
    consult: false, recommend: 12,
    monthlySales: 218, monthlyRevenue: 13_080_000 },
  { id: "nc-8", code: "DT-TH-01", name: "부분비만 매선", category: "diet",
    tagline: "복부·허벅지·팔뚝",
    duration: 60, price: 220000, memberPrice: 198000,
    room: "시술실 2", staff: "박서윤 원장",
    consult: true, recommend: 6,
    monthlySales: 26, monthlyRevenue: 5_720_000 },
  { id: "nc-9", code: "DT-CX-01", name: "카복시 (1회)", category: "diet",
    tagline: "CO₂ 가스 시술 · 부분 부종",
    duration: 25, price: 80000, memberPrice: 72000,
    room: "시술실 2", staff: "박서윤 원장",
    consult: false, recommend: 8,
    monthlySales: 49, monthlyRevenue: 3_920_000 },
  { id: "nc-10", code: "DT-IN-01", name: "인바디 + 체성분 상담", category: "diet",
    tagline: "측정 + 분석 리포트 · 25분",
    duration: 25, price: 30000, memberPrice: 27000,
    room: "상담실 1", staff: "한지원 영양사",
    consult: false, recommend: 2,
    monthlySales: 132, monthlyRevenue: 3_960_000 },

  // 체형 (Body)
  { id: "nc-11", code: "BD-CH-01", name: "자비 추나 (체형 교정)", category: "body",
    tagline: "거북목·골반·자세 · 보험 외",
    duration: 40, price: 80000, memberPrice: 72000,
    room: "추나실", staff: "오한결 추나전문의",
    consult: false, recommend: 12,
    monthlySales: 86, monthlyRevenue: 6_880_000 },
  { id: "nc-12", code: "BD-CP-01", name: "셀룰라이트 부항", category: "body",
    tagline: "허벅지·복부 · 30분",
    duration: 30, price: 50000, memberPrice: 45000,
    room: "시술실 2", staff: "박서윤 원장",
    consult: false, recommend: 6,
    monthlySales: 41, monthlyRevenue: 2_050_000 },
  { id: "nc-13", code: "BD-LM-01", name: "림프 마사지", category: "body",
    tagline: "부종·순환 케어 · 50분",
    duration: 50, price: 70000, memberPrice: 63000,
    room: "마사지실", staff: "정수현 치료사",
    consult: false, recommend: 6,
    monthlySales: 58, monthlyRevenue: 4_060_000 },

  // 피부 (Skin)
  { id: "nc-14", code: "SK-PC-01", name: "여드름 약침", category: "skin",
    tagline: "트러블·염증 · 25분",
    duration: 25, price: 55000, memberPrice: 49500,
    room: "약침실", staff: "이지영 부원장",
    consult: false, recommend: 8,
    monthlySales: 67, monthlyRevenue: 3_685_000 },
  { id: "nc-15", code: "SK-HM-01", name: "아토피 한약", category: "skin",
    tagline: "체질 개선 · 1개월",
    duration: 30, price: 320000, memberPrice: 288000,
    room: "상담실 2", staff: "김민준 원장",
    consult: true, recommend: 3,
    monthlySales: 14, monthlyRevenue: 4_480_000 },

  // 모발 (Hair)
  { id: "nc-16", code: "HR-PC-01", name: "발모 약침", category: "hair",
    tagline: "두피 혈자리 자극 · 30분",
    duration: 30, price: 70000, memberPrice: 63000,
    room: "약침실", staff: "이지영 부원장",
    consult: false, recommend: 12,
    monthlySales: 92, monthlyRevenue: 6_440_000,
    badge: "NEW" },
  { id: "nc-17", code: "HR-SC-01", name: "두피 케어 (한방)", category: "hair",
    tagline: "한방 헤어팩 + 두피 마사지 · 45분",
    duration: 45, price: 60000, memberPrice: 54000,
    room: "마사지실", staff: "정수현 치료사",
    consult: false, recommend: 8,
    monthlySales: 36, monthlyRevenue: 2_160_000 },
];

// ── 오늘 시술 일정 (2026-05-23 기준) ─────────────────────────────
const NC_TODAY_SCHEDULE = [
  { id: "s1", time: "09:30", patient: "김지수", chartNo: "C-1041", procedureId: "nc-1",
    status: "done", staff: "이지영 부원장", paid: 79200 },
  { id: "s2", time: "10:00", patient: "박서연", chartNo: "C-1209", procedureId: "nc-7",
    status: "done", staff: "이지영 부원장", paid: 54000 },
  { id: "s3", time: "10:30", patient: "정유진", chartNo: "C-0788", procedureId: "nc-6",
    status: "done", staff: "박서윤 원장", paid: 342000 },
  { id: "s4", time: "11:00", patient: "이서연", chartNo: "C-1322", procedureId: "nc-2",
    status: "in_progress", staff: "김민준 원장", paid: 252000 },
  { id: "s5", time: "11:00", patient: "최민호", chartNo: "C-1180", procedureId: "nc-11",
    status: "in_progress", staff: "오한결 추나전문의", paid: 72000 },
  { id: "s6", time: "11:30", patient: "한가람", chartNo: "C-0921", procedureId: "nc-4",
    status: "ready", staff: "이지영 부원장", paid: 49500 },
  { id: "s7", time: "13:00", patient: "오한결", chartNo: "C-1015", procedureId: "nc-16",
    status: "scheduled", staff: "이지영 부원장", paid: 63000 },
  { id: "s8", time: "13:30", patient: "강하늘", chartNo: "C-0833", procedureId: "nc-9",
    status: "scheduled", staff: "박서윤 원장", paid: 72000 },
  { id: "s9", time: "14:00", patient: "윤도현", chartNo: "C-0612", procedureId: "nc-3",
    status: "scheduled", staff: "김민준 원장", paid: 315000 },
  { id: "s10", time: "14:30", patient: "신유나", chartNo: "C-1444", procedureId: "nc-7",
    status: "scheduled", staff: "이지영 부원장", paid: 54000 },
  { id: "s11", time: "15:00", patient: "장우성", chartNo: "C-1356", procedureId: "nc-12",
    status: "scheduled", staff: "박서윤 원장", paid: 45000 },
  { id: "s12", time: "15:30", patient: "송다은", chartNo: "C-1290", procedureId: "nc-1",
    status: "scheduled", staff: "이지영 부원장", paid: 79200 },
  { id: "s13", time: "16:00", patient: "황민지", chartNo: "C-1502", procedureId: "nc-13",
    status: "scheduled", staff: "정수현 치료사", paid: 63000 },
  { id: "s14", time: "16:30", patient: "백수진", chartNo: "C-1487", procedureId: "nc-10",
    status: "scheduled", staff: "한지원 영양사", paid: 27000 },
  { id: "s15", time: "17:00", patient: "권태우", chartNo: "C-1099", procedureId: "nc-14",
    status: "scheduled", staff: "이지영 부원장", paid: 49500 },
];

const NC_SCHEDULE_STATUS = {
  done:        { label: "완료",     fg: "var(--text-muted)",         bg: "var(--bg-raised)",        dot: "var(--ink-300)",     icon: "check" },
  in_progress: { label: "진행중",   fg: "var(--text-brand)",         bg: "var(--brand-subtle)",     dot: "var(--jade-500)",    icon: "play" },
  ready:       { label: "대기",     fg: "var(--status-warning-text)",bg: "var(--status-warning-bg)",dot: "var(--amber-500)",   icon: "hourglass" },
  scheduled:   { label: "예약",     fg: "var(--text-secondary)",     bg: "var(--bg-surface)",       dot: "var(--ink-200)",     icon: "calendar" },
};

// ── 상담 보드 (kanban: 신규 → 상담예약 → 견적 → 결정대기 → 전환완료) ─
const NC_CONSULT_STAGES = [
  { key: "new",       label: "신규 문의",  icon: "inbox",          fg: "var(--text-secondary)", bg: "var(--bg-raised)" },
  { key: "scheduled", label: "상담 예약",  icon: "calendar-plus",  fg: "var(--accent-marine)",  bg: "var(--accent-marine-bg)" },
  { key: "quoted",    label: "견적 발송",  icon: "file-text",      fg: "var(--amber-700)",      bg: "var(--status-warning-bg)" },
  { key: "decision",  label: "결정 대기",  icon: "clock",          fg: "var(--pink-700)",       bg: "var(--pink-100)" },
  { key: "won",       label: "전환 완료",  icon: "check-circle-2", fg: "var(--text-brand)",     bg: "var(--brand-subtle)" },
];

const NC_CONSULT_LEADS = [
  { id: "L-001", patient: "이주아", phone: "010-1188-2233", age: 28, gender: "여",
    interest: "nc-2", source: "인스타", quoted: null, stage: "new", lastTouch: "30분 전",
    note: "친구 추천으로 매선 가격 문의" },
  { id: "L-002", patient: "조은서", phone: "010-3344-5566", age: 34, gender: "여",
    interest: "nc-6", source: "검색", quoted: null, stage: "new", lastTouch: "1시간 전",
    note: "출산 후 다이어트 한약 상담 희망" },
  { id: "L-003", patient: "박지원", phone: "010-2233-4455", age: 31, gender: "여",
    interest: "nc-1", source: "지인소개", quoted: null, stage: "scheduled", lastTouch: "내일 14:00",
    note: "친구 김지수님 소개" },
  { id: "L-004", patient: "윤소민", phone: "010-9988-7766", age: 27, gender: "여",
    interest: "nc-3", source: "인스타", quoted: null, stage: "scheduled", lastTouch: "내일 16:00",
    note: "V라인 매선 1차 상담" },
  { id: "L-005", patient: "한도윤", phone: "010-7777-1234", age: 41, gender: "남",
    interest: "nc-16", source: "검색", quoted: 504000, stage: "quoted", lastTouch: "어제",
    note: "발모 약침 8회 패키지 견적 발송" },
  { id: "L-006", patient: "임가영", phone: "010-4567-8901", age: 36, gender: "여",
    interest: "nc-6", source: "전화", quoted: 342000, stage: "quoted", lastTouch: "2일 전",
    note: "비만 한약 1개월 견적 · 가족 할인 문의" },
  { id: "L-007", patient: "정재호", phone: "010-2345-6789", age: 39, gender: "남",
    interest: "nc-11", source: "지인소개", quoted: 720000, stage: "decision", lastTouch: "3일 전",
    note: "10회 패키지 결정 대기 · 배우자와 상의" },
  { id: "L-008", patient: "고민서", phone: "010-3456-7890", age: 29, gender: "여",
    interest: "nc-2", source: "인스타", quoted: 252000, stage: "decision", lastTouch: "4일 전",
    note: "결혼식 D-30, 회신 필요" },
  { id: "L-009", patient: "노윤정", phone: "010-5678-9012", age: 33, gender: "여",
    interest: "nc-6", source: "지인소개", quoted: 342000, stage: "won", lastTouch: "오늘 09:30",
    note: "결제 완료 · 다음주 첫 상담" },
  { id: "L-010", patient: "강예린", phone: "010-6789-0123", age: 26, gender: "여",
    interest: "nc-7", source: "인스타", quoted: 540000, stage: "won", lastTouch: "오늘 11:15",
    note: "10회 패키지 결제" },
];

// ── 최근 시술받은 환자 매트릭스 (추천 환자) ──────────────────────
const NC_RECOMMEND_PATIENTS = [
  { id: 1, name: "김지수", chartNo: "C-1041", lastVisit: "오늘",     ageGender: "여 · 34",
    history: ["nc-1", "nc-7"], totalPaid: 824000, recommendId: "nc-2", score: 92,
    reason: "안면 미용침 6회 이상 — 매선 단계 권유" },
  { id: 2, name: "박서연", chartNo: "C-1209", lastVisit: "오늘",     ageGender: "여 · 28",
    history: ["nc-7"], totalPaid: 432000, recommendId: "nc-9", score: 86,
    reason: "다이어트 침 10회 — 카복시 병행 효과↑" },
  { id: 3, name: "정유진", chartNo: "C-0788", lastVisit: "오늘",     ageGender: "여 · 46",
    history: ["nc-6"], totalPaid: 1_140_000, recommendId: "nc-15", score: 78,
    reason: "보약 복용 이력 — 환절기 아토피 한약 가능" },
  { id: 4, name: "이서연", chartNo: "C-1322", lastVisit: "오늘",     ageGender: "여 · 33",
    history: ["nc-2"], totalPaid: 252000, recommendId: "nc-4", score: 74,
    reason: "매선 후 미백 약침 패키지 일반 코스" },
  { id: 5, name: "한가람", chartNo: "C-0921", lastVisit: "어제",     ageGender: "여 · 31",
    history: ["nc-4", "nc-5"], totalPaid: 195000, recommendId: "nc-1", score: 88,
    reason: "약침 6회 — 미용침 정기 권유 시점" },
  { id: 6, name: "오한결", chartNo: "C-1015", lastVisit: "이번주",   ageGender: "남 · 38",
    history: ["nc-11"], totalPaid: 320000, recommendId: "nc-16", score: 82,
    reason: "체형 케어 중 — 두피 약침 신규 관심 표명" },
  { id: 7, name: "장우성", chartNo: "C-1356", lastVisit: "이번주",   ageGender: "남 · 41",
    history: ["nc-7", "nc-12"], totalPaid: 158000, recommendId: "nc-9", score: 80,
    reason: "다이어트 침 + 부항 — 카복시 추천 가능" },
];

const NC_KRW = n => "₩" + (n || 0).toLocaleString("ko-KR");

Object.assign(window, {
  NC_CATEGORIES, NC_TONES, NC_PROCEDURES,
  NC_TODAY_SCHEDULE, NC_SCHEDULE_STATUS,
  NC_CONSULT_STAGES, NC_CONSULT_LEADS,
  NC_RECOMMEND_PATIENTS, NC_KRW,
});
