// KoMES — Staff (직원) data
// 한의원 직원 마스터: 한의사 / 간호(조무)사 / 원무 / 물리치료사 / 한약사 / 행정

const STAFF_MASTER = [
  {
    id: 1, name: "김민준", role: "원장", roleKey: "doctor", dept: "진료부",
    licenses: ["한의사 면허 #12345"], specialty: "침구·내과",
    phone: "010-2233-1100", email: "minjun.kim@komes.kr",
    joinDate: "2018-03-02", status: "active", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "휴진", 금: "09–18", 토: "09–13", 일: "휴진" },
    todayHours: "09:00 – 18:00",
    permissions: ["원장", "차트 작성", "처방 권한", "통계 열람", "직원 관리", "급여 관리"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 15, used: 4 },
    note: "대표원장. 매주 목요일 외부 자문.",
    color: "#3A7065",
    todayStatus: "진료중", // 진료중 | 진료대기 | 휴식 | 부재
    todayPatients: 14,
  },
  {
    id: 2, name: "이서연", role: "부원장", roleKey: "doctor", dept: "진료부",
    licenses: ["한의사 면허 #18829"], specialty: "부인과·소아",
    phone: "010-7711-2244", email: "seoyeon.lee@komes.kr",
    joinDate: "2020-09-01", status: "active", workType: "정규직",
    schedule: { 월: "10–19", 화: "10–19", 수: "휴진", 목: "10–19", 금: "10–19", 토: "10–14", 일: "휴진" },
    todayHours: "10:00 – 19:00",
    permissions: ["차트 작성", "처방 권한", "통계 열람"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 15, used: 6 },
    note: "",
    color: "#4A7C6F",
    todayStatus: "진료중",
    todayPatients: 11,
  },
  {
    id: 3, name: "박지혜", role: "수간호사", roleKey: "nurse", dept: "간호부",
    licenses: ["간호사 면허 #RN-44218"], specialty: "수간호 · 침구 보조",
    phone: "010-5566-3322", email: "jihye.park@komes.kr",
    joinDate: "2019-04-15", status: "active", workType: "정규직",
    schedule: { 월: "08:30–18", 화: "08:30–18", 수: "08:30–18", 목: "08:30–18", 금: "08:30–18", 토: "08:30–13", 일: "휴무" },
    todayHours: "08:30 – 18:00",
    permissions: ["차트 보조 작성", "예약 관리", "수납", "재고 조정", "직원 일정 관리"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 15, used: 8 },
    note: "간호팀 리더. 신규 입사자 교육 담당.",
    color: "#C4974B",
    todayStatus: "진료중",
    todayPatients: 24,
  },
  {
    id: 4, name: "정수민", role: "간호조무사", roleKey: "nurse", dept: "간호부",
    licenses: ["간호조무사 자격 #NA-9821"], specialty: "물리치료 보조",
    phone: "010-2244-7711", email: "sumin.jung@komes.kr",
    joinDate: "2023-02-01", status: "active", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "09–18", 금: "09–18", 토: "휴무", 일: "휴무" },
    todayHours: "09:00 – 18:00",
    permissions: ["차트 보조 작성", "예약 관리", "수납"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 12, used: 3 },
    note: "",
    color: "#C4974B",
    todayStatus: "진료중",
    todayPatients: 16,
  },
  {
    id: 5, name: "한지원", role: "원무실장", roleKey: "admin", dept: "원무부",
    licenses: [], specialty: "보험 청구 · 수납",
    phone: "010-8800-9911", email: "jiwon.han@komes.kr",
    joinDate: "2017-06-10", status: "active", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "09–18", 금: "09–18", 토: "09–13", 일: "휴무" },
    todayHours: "09:00 – 18:00",
    permissions: ["예약 관리", "수납", "보험 청구", "통계 열람", "급여 관리"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 15, used: 7 },
    note: "원무팀 리더. 보험 청구 총괄.",
    color: "#5A6E8A",
    todayStatus: "진료중",
    todayPatients: null,
  },
  {
    id: 6, name: "최영호", role: "원무직원", roleKey: "admin", dept: "원무부",
    licenses: [], specialty: "접수 · 수납",
    phone: "010-3300-7788", email: "youngho.choi@komes.kr",
    joinDate: "2024-01-08", status: "active", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "09–18", 금: "09–18", 토: "휴무", 일: "휴무" },
    todayHours: "09:00 – 18:00",
    permissions: ["예약 관리", "수납"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 12, used: 2 },
    note: "",
    color: "#5A6E8A",
    todayStatus: "휴식",
    todayPatients: null,
  },
  {
    id: 7, name: "윤다영", role: "물리치료사", roleKey: "therapist", dept: "치료부",
    licenses: ["물리치료사 면허 #PT-3321"], specialty: "도수·전기치료",
    phone: "010-6677-4422", email: "dayoung.yoon@komes.kr",
    joinDate: "2022-05-16", status: "active", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "휴무", 금: "09–18", 토: "09–13", 일: "휴무" },
    todayHours: "09:00 – 18:00",
    permissions: ["치료 기록 작성", "예약 관리"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 12, used: 5 },
    note: "",
    color: "#B5873E",
    todayStatus: "진료중",
    todayPatients: 9,
  },
  {
    id: 8, name: "송미라", role: "간호사", roleKey: "nurse", dept: "간호부",
    licenses: ["간호사 면허 #RN-50912"], specialty: "침구 보조",
    phone: "010-9911-5544", email: "mira.song@komes.kr",
    joinDate: "2024-08-19", status: "leave", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "09–18", 금: "09–18", 토: "휴무", 일: "휴무" },
    todayHours: "—",
    permissions: ["차트 보조 작성", "예약 관리"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 12, used: 12 },
    note: "출산 휴가 중 (2026-03-04 ~ 2026-09-04).",
    color: "#C4974B",
    todayStatus: "휴직",
    todayPatients: null,
  },
  {
    id: 9, name: "강태우", role: "한약사", roleKey: "pharmacist", dept: "조제실",
    licenses: ["한약사 면허 #KP-2210"], specialty: "탕전·조제",
    phone: "010-4455-2200", email: "taewoo.kang@komes.kr",
    joinDate: "2021-11-22", status: "active", workType: "정규직",
    schedule: { 월: "09–18", 화: "09–18", 수: "09–18", 목: "09–18", 금: "09–18", 토: "휴무", 일: "휴무" },
    todayHours: "09:00 – 18:00",
    permissions: ["조제 권한", "약재 재고 관리", "발주"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 15, used: 4 },
    note: "",
    color: "#7A6E60",
    todayStatus: "진료중",
    todayPatients: null,
  },
  {
    id: 10, name: "임수아", role: "행정직원", roleKey: "admin", dept: "원무부",
    licenses: [], specialty: "총무 · 회계",
    phone: "010-1122-9988", email: "sua.lim@komes.kr",
    joinDate: "2023-07-03", status: "active", workType: "파트타임",
    schedule: { 월: "13–18", 화: "13–18", 수: "13–18", 목: "13–18", 금: "13–18", 토: "휴무", 일: "휴무" },
    todayHours: "13:00 – 18:00",
    permissions: ["예약 조회", "통계 열람"],
    salary: { type: "시급제", visible: false },
    leaveBalance: { annual: 8, used: 1 },
    note: "오후 근무.",
    color: "#5A6E8A",
    todayStatus: "진료대기",
    todayPatients: null,
  },
  {
    id: 11, name: "오재훈", role: "한의사", roleKey: "doctor", dept: "진료부",
    licenses: ["한의사 면허 #20114"], specialty: "추나·근골격계",
    phone: "010-7700-3311", email: "jaehoon.oh@komes.kr",
    joinDate: "2025-03-01", status: "active", workType: "정규직",
    schedule: { 월: "14–21", 화: "14–21", 수: "14–21", 목: "14–21", 금: "14–21", 토: "휴진", 일: "휴진" },
    todayHours: "14:00 – 21:00",
    permissions: ["차트 작성", "처방 권한"],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 12, used: 1 },
    note: "야간 진료 담당.",
    color: "#4A7C6F",
    todayStatus: "진료대기",
    todayPatients: 0,
  },
  {
    id: 12, name: "장은비", role: "간호조무사", roleKey: "nurse", dept: "간호부",
    licenses: ["간호조무사 자격 #NA-1188"], specialty: "수납 보조",
    phone: "010-3344-1199", email: "eunbi.jang@komes.kr",
    joinDate: "2022-04-12", status: "resigned", workType: "정규직",
    schedule: { 월: "—", 화: "—", 수: "—", 목: "—", 금: "—", 토: "—", 일: "—" },
    todayHours: "—",
    permissions: [],
    salary: { type: "월급제", visible: false },
    leaveBalance: { annual: 0, used: 0 },
    note: "2026-02-28 퇴사. 이직.",
    color: "#9A8E82",
    todayStatus: "퇴직",
    todayPatients: null,
  },
];

const ROLE_GROUPS = [
  { key: "doctor",     label: "한의사",     icon: "stethoscope",   color: "#3A7065" },
  { key: "nurse",      label: "간호직",     icon: "heart-pulse",   color: "#C4974B" },
  { key: "admin",      label: "원무·행정", icon: "clipboard-list", color: "#5A6E8A" },
  { key: "therapist",  label: "물리치료사", icon: "hand-helping",   color: "#B5873E" },
  { key: "pharmacist", label: "한약사",     icon: "flask-conical", color: "#7A6E60" },
];

const STATUS_META = {
  active:   { label: "재직",  bg: "var(--jade-50)",     color: "var(--jade-700)",     border: "var(--jade-200)",     dot: "var(--jade-500)" },
  leave:    { label: "휴직",  bg: "var(--amber-100)",   color: "var(--amber-700)",    border: "var(--amber-200)",    dot: "var(--amber-500)" },
  resigned: { label: "퇴직",  bg: "var(--stone-200)",   color: "var(--ink-600)",      border: "var(--stone-300)",    dot: "var(--ink-300)" },
};

const TODAY_STATUS_META = {
  진료중:   { color: "var(--jade-700)",     bg: "var(--jade-100)",     dot: "var(--jade-500)" },
  진료대기: { color: "var(--amber-700)",    bg: "var(--amber-100)",    dot: "var(--amber-500)" },
  휴식:     { color: "var(--ink-600)",      bg: "var(--stone-200)",    dot: "var(--ink-300)" },
  부재:     { color: "var(--cinnabar-700)", bg: "var(--cinnabar-100)", dot: "var(--cinnabar-500)" },
  휴직:     { color: "var(--amber-700)",    bg: "var(--amber-100)",    dot: "var(--amber-500)" },
  퇴직:     { color: "var(--ink-600)",      bg: "var(--stone-200)",    dot: "var(--ink-300)" },
};

Object.assign(window, { STAFF_MASTER, ROLE_GROUPS, STATUS_META, TODAY_STATUS_META });
